//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class addressbook
    {
        public string addressId { get; set; }
        public string contectName { get; set; }
        public string companyName { get; set; }
        public string addressLn1 { get; set; }
        public string addressLn2 { get; set; }
        public string addressLn3 { get; set; }
        public string postcode { get; set; }
        public string phoneNo { get; set; }
        public string faxNo { get; set; }
        public string accountID { get; set; }
        public string region { get; set; }
        public string telexNo { get; set; }
    }
}
