//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class airwaybill
    {
        public string shippingNo { get; set; }
        public string packageID { get; set; }
        public string accID { get; set; }
        public double shippingExpenses { get; set; }
        public System.DateTime date { get; set; }
        public string service { get; set; }
        public double length { get; set; }
        public double width { get; set; }
        public double height { get; set; }
        public double weight { get; set; }
        public string destinationTax { get; set; }
        public string transportCharge { get; set; }
        public string typeOfExport { get; set; }
    }
}
