//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingorder
    {
        public string bookingID { get; set; }
        public string accID { get; set; }
        public string addrID { get; set; }
        public System.DateTime datetime { get; set; }
        public string serviceType { get; set; }
        public double totalExpenses { get; set; }
        public string status { get; set; }
        public string pickupDate { get; set; }
        public string pickupTime { get; set; }
    }
}
