//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class commercialinvoice
    {
        public string invoiceID { get; set; }
        public string accountID { get; set; }
        public string packageID { get; set; }
        public double totalValue { get; set; }
        public System.DateTime creationDate { get; set; }
    }
}
