//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditcard
    {
        public string cardID { get; set; }
        public string accountID { get; set; }
        public string cardNo { get; set; }
        public string cardType { get; set; }
        public System.DateTime expiryDate { get; set; }
        public string holderName { get; set; }
    }
}
