//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobtitle
    {
        public int jobID { get; set; }
        public string jobName { get; set; }
    }
}
