//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public string accountID { get; set; }
        public string actionPerformed { get; set; }
        public int logID { get; set; }
        public Nullable<System.DateTime> times { get; set; }
        public string ipAddress { get; set; }
    }
}
