//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edeaccountEntities : DbContext
    {
        public edeaccountEntities()
            : base("name=edeaccountEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addressbook> addressbook { get; set; }
        public virtual DbSet<airwaybill> airwaybill { get; set; }
        public virtual DbSet<bookingorder> bookingorder { get; set; }
        public virtual DbSet<centre> centre { get; set; }
        public virtual DbSet<commercialinvoice> commercialinvoices { get; set; }
        public virtual DbSet<consolidatemonthlyinvoice> consolidatemonthlyinvoice { get; set; }
        public virtual DbSet<creditcard> creditcard { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<jobtitle> jobtitle { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<paymentrecord> paymentrecord { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<importinvoice> importinvoices { get; set; }
        public virtual DbSet<prealertrecord> prealertrecord { get; set; }
    }
}
