//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        public string packageID { get; set; }
        public string accID { get; set; }
        public string bookingID { get; set; }
        public string pkgName { get; set; }
        public string packageType { get; set; }
        public string serviceType { get; set; }
        public bool isImport { get; set; }
        public int qty { get; set; }
        public string unit { get; set; }
        public double unitValue { get; set; }
        public Nullable<System.DateTime> statusTime { get; set; }
        public Nullable<bool> cusConfirm { get; set; }
        public string addrID { get; set; }
        public string status { get; set; }
        public Nullable<int> isComplete { get; set; }
        public string location { get; set; }
        public string centreID { get; set; }
        public string staffID { get; set; }
        public string remark { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> expense { get; set; }
    }
}
