//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentrecord
    {
        public string paymentID { get; set; }
        public string accountID { get; set; }
        public System.DateTime payDateTime { get; set; }
        public string payMethod { get; set; }
        public string cardID { get; set; }
        public double payValue { get; set; }
        public string centreID { get; set; }
        public string stfID { get; set; }
    }
}
