//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDEapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class prealertrecord
    {
        public int messageID { get; set; }
        public string packageID { get; set; }
        public string pkgName { get; set; }
        public string accID { get; set; }
        public int statusID { get; set; }
        public string message { get; set; }
        public int isRead { get; set; }
        public System.DateTime timeUpdated { get; set; }
    }
}
